version: '3.6'

services:
  db:
    image: mariadb:12.2@sha256:e16f61b8f6ed25111adbb1c5c19bbc2904efc8ed14029999af0cbe1c7ae18bf1
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.3

  wordpress:
    image: wordpress:apache@sha256:ee74dc0ebbe7ec43b7f473c0fb4f1dfb6b211d7785f0a95bcdfa10e628c2e67f
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-login-logger

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24