version: '3.6'

services:
  db:
    image: mariadb:12.3@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.3

  wordpress:
    image: wordpress:apache@sha256:65919a9ca10940feb10d9400fead0d639bf86241f47c91e2b9ea4703aa8452cf
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-login-logger

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24