version: '3.6'

services:
  db:
    image: mariadb:12.3@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.3

  wordpress:
    image: wordpress:apache@sha256:b2d7e3153c8a96f90305a3102fb6439335237fb1a9655b617d15c5168ce2f7a3
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.21.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/wp-login-logger

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24